import Footers from "@/components/layouts/Footers";
import Navbar from "@/components/layouts/Navbar";
import { Poppins } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const fontBangla = localFont(
  {
    src: "../fonts/mayaboti-normal.ttf"
  }
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar />
        </header>
        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-313px)]">{children}</main>
        <footer>
          <Footers />
        </footer>
      </body>
    </html>
  );
}
